project_id = "ounhzchuuvziyqriyjdb"

[functions.setup-platform-admin]
verify_jwt = false

[functions.reset-monthly-payments]
verify_jwt = false

[functions.monthly-report]
verify_jwt = false

[functions.run-membership-progression]
verify_jwt = false

[functions.process-idp]
verify_jwt = false

[functions.send-idp-report]
verify_jwt = false

[functions.idp-maintenance]
verify_jwt = false
